### ISSUE TITLE
None default namespace application

### ISSUE THREAD

**Issue by apburton84** [nilportugues/laravel5-jsonapi#21]
```Fatal error: Class 'App\Http\Controllers\Controller' not found in vendor/nilportugues/laravel5-json-api/src/NilPortugues/Laravel5/JsonApi/Controller/JsonApiController.php on line 33```

Composer.json

```
"autoload": {
        "psr-4": {
            "MyApp\\V3core\\": "app/"
        },
        "classmap": [
            "database/"
        ]
}
```
As our namespace is not `App`

maybe the solution would be  using `Laravel\Lumen\Routing\Controller` as `App\Controller` is an extension of it.

**Comment by gharding** [comment]
Just started using this application and considered the same thing under Laravel.

If a developer uses this repository with a non-standard top-level namespace then `App\Http\Controller` will not be found.

IMO the dependency should be on the classes contained in the framework - in Laravel's case the parent controller class is `Illuminate\Routing\Controller`.
To further this argument `App\Controller` in both Laravel and Lumen is empty by default and therefore only contains the functionality for their parent classes.

**Comment by nilportugues** [comment]
- I will look into this tonight and push a fix for this. Inheriting from `Illuminate\Routing\Controller` seems like the right choice here.

- In the routing it should be possible to user-define other than `App\Http\Controller`. In fact, in the test files for this library, that uses Laravel, I'm using `NilPortugues\Tests\App\Controller` for the Controller's namespace. Either case, I'll check again, and document it.

**Comment by nilportugues** [comment]
@gharding @apburton84 JsonApiController` controller now extends from `Illuminate\Routing\Controller`.... with release 2.1.6 8 (see https://github.com/nilportugues/laravel5-jsonapi/commit/35a8d87234ff5c631738e4fdac81ba96feab999b)

Did not investigate the namespaces issues you're experiencing yet.

**Comment by gharding** [comment]
@nilportugues 

The non-standard namespacing issue comes from the fact that `App\Http\Controller` is hard-coded in `NilPortugues\Laravel5\JsonApi\Controller\JsonApiController`.

The latest fix will work perfectly for Laravel (I've tested it, and it's all good) however this won't fix the issue for Lumen users. `Illuminate\Routing\Controller` is not present in Lumen, so this will only swap out one exception for another for these users unless they are, for some reason, using both frameworks.

I realise that this won't be an easy fix because of the lack of a standard controller shared by Lumen and Laravel which I assume was the rationale for extending from `App\Http\Controllers\Controller` in the first place. 

My suggestion would be to ask the user to define the namespace of their base controller in a config file and then pick that up as `JsonApiController`'s parent class.

**Comment by nilportugues** [comment]
Lumen users should use LumenJsonApiController. 

@gharding @apburton84
https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.1.8
