### ISSUE TITLE
getAlias value not mirrored in response

### ISSUE THREAD

**Issue by OskarD** [nilportugues/laravel5-jsonapi#43]
I have this code in my PartiesTransformer class

    public function getAlias()
    {
        return 'party';
    }

but when I GET the list of the resource, it shows `"type": "parties"`

**Comment by nilportugues** [comment]
Make sure the Parties class is mapped in the public function getClass(). Otherwise it won't change the name.

Check the tests directory, where this is actually done:

- The transformer: https://github.com/nilportugues/laravel5-jsonapi/blob/master/tests/NilPortugues/App/Transformers/EmployeesTransformer.php

- The result: https://github.com/nilportugues/laravel5-jsonapi/blob/master/tests/NilPortugues/Laravel5/JsonApi/JsonApiControllerTest.php#L77
